use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let manifest_path = Path::new(&manifest_dir);

    // Load .env file generated by bundle-tenant.py (if present)
    // Falls back gracefully when building without the bundler
    let env_path = manifest_path.join(".env");
    if env_path.exists() {
        let env_content = fs::read_to_string(&env_path).unwrap_or_default();
        for line in env_content.lines() {
            let line = line.trim();
            if line.starts_with("TENANT_CONFIG=") {
                let value = line["TENANT_CONFIG=".len()..].trim();
                // Remove surrounding quotes if present
                let value = value.trim_matches('"').trim_matches('\'');
                env::set_var("TENANT_CONFIG", value);
                break;
            }
        }
    }

    // Track tenant config changes for rebuild
    // TENANT_CONFIG is set by bundle-tenant.py via .env
    // Falls back to legacy default for backward compatibility
    let tenant_config_path = env::var("TENANT_CONFIG")
        .unwrap_or_else(|_| manifest_path.join("../tenant-configs/default.json").to_string_lossy().into_owned());

    let config_path = Path::new(&tenant_config_path);
    if config_path.exists() {
        println!("cargo:rerun-if-changed={}", config_path.display());

        // Read and copy tenant config to OUT_DIR for runtime inclusion
        let out_dir = env::var("OUT_DIR").unwrap();
        let dest_path = Path::new(&out_dir).join("tenant-config.json");
        fs::copy(config_path, &dest_path)
            .expect("Failed to copy tenant config to OUT_DIR");

        // Parse to validate JSON
        let config_str = fs::read_to_string(config_path)
            .expect("Failed to read tenant config");
        let config: serde_json::Value = serde_json::from_str(&config_str)
            .expect("Tenant config is not valid JSON");

        // Emit env var for runtime access to the config file path
        println!("cargo:rustc-env=TENANT_CONFIG_PATH={}", dest_path.display());

        // Also embed the config JSON content as an env var so any crate can read it at compile time.
        // MUST use compact JSON (no newlines) — cargo:rustc-env reads line-by-line and
        // newlines in the value would truncate the embedded content.
        let compact_json = serde_json::to_string(&config)
            .expect("Failed to compact tenant config JSON for env var");
        println!("cargo:rustc-env=TENANT_CONFIG_JSON={}", compact_json);

        // Copy the tenant config to a fixed location that all workspace crates can include_str! from
        let shared_dest = manifest_path.join("tenant-config-embedded.json");
        fs::write(&shared_dest, &config_str).expect("Failed to write shared tenant config");

        // Generate Rust module with embedded config for compile-time inclusion
        generate_tenant_config_module(&config_str, &Path::new(&out_dir));

        // Template tauri.conf.json with tenant-specific values
        let tenant_id = config["tenant"]["id"].as_str().unwrap_or("default");
        let commercial_name = config["tenant"]["commercialName"].as_str().unwrap_or("MindLedger");

        // Bundle runtime DLLs on Windows targets (OpenSSL + WebView2)
        let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
        let resources = if target_os == "windows" {
            let mut r = bundle_openssl_dlls(manifest_path);
            r.extend(bundle_webview2_loader(manifest_path));
            r
        } else {
            vec![]
        };

        template_tauri_conf(tenant_id, commercial_name, &resources, Path::new(&out_dir));
    }

    tauri_build::build()
}

/// Copy OpenSSL DLLs from vcpkg to resources/ and return their relative paths for bundling.
/// Detects target architecture to use correct DLL names (x64 vs arm64).
/// Uses CARGO_CFG_TARGET_ARCH (set by cargo) for reliable arch detection.
fn bundle_openssl_dlls(manifest_path: &Path) -> Vec<String> {
    let target_arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
    let arch_suffix = if target_arch == "aarch64" {
        "arm64"
    } else {
        "x64"
    };

    // Dynamic triplet provides both import libs (.lib) and DLLs (.dll)
    // vcpkg triplet: x64-windows (dynamic) or arm64-windows (dynamic)
    let openssl_base = env::var("OPENSSL_DIR")
        .map(|p| Path::new(&p).join("bin"))
        .unwrap_or_else(|_| {
            // Fallback: try user's scoop MinGW
            let home = env::var("USERPROFILE").unwrap_or_default();
            Path::new(&home).join("scoop/apps/mingw/current/opt/bin")
        });

    let resources_dir = manifest_path.join("resources/openssl");
    let _ = fs::create_dir_all(&resources_dir);

    let mut resources = vec![];

    // Build priority list: arch-specific first, then generic
    let crypto_candidates = [
        format!("libcrypto-3-{}.dll", arch_suffix),
        "libcrypto-3.dll".to_string(),
        "libcrypto.dll".to_string(),
    ];
    let ssl_candidates = [
        format!("libssl-3-{}.dll", arch_suffix),
        "libssl-3.dll".to_string(),
        "libssl.dll".to_string(),
    ];

    for dll_candidates in [&crypto_candidates, &ssl_candidates] {
        let mut found = false;
        let prefix = if dll_candidates[0].contains("crypto") { "libcrypto" } else { "libssl" };
        for dll_name in dll_candidates {
            let src = openssl_base.join(dll_name);
            if src.exists() {
                let dst = resources_dir.join(dll_name);
                let _ = fs::copy(&src, &dst);
                resources.push(format!("resources/openssl/{}", dll_name));
                println!("cargo:warning=Bundled OpenSSL DLL: {}", dll_name);
                found = true;
                break;
            }
        }
        if !found {
            // Last resort: scan directory for any matching DLL
            if let Ok(entries) = fs::read_dir(&openssl_base) {
                for entry in entries.flatten() {
                    let name = entry.file_name().to_string_lossy().to_string();
                    if name.starts_with(prefix) && name.ends_with(".dll") {
                        let dst = resources_dir.join(&name);
                        let _ = fs::copy(entry.path(), &dst);
                        resources.push(format!("resources/openssl/{}", name));
                        println!("cargo:warning=Bundled OpenSSL DLL (discovered): {}", name);
                        found = true;
                        break;
                    }
                }
            }
            if !found {
                println!("cargo:warning=No OpenSSL {} DLL found in {}", prefix, openssl_base.display());
            }
        }
    }
    resources
}

/// Copy WebView2Loader.dll from pre-staged resources/ to OUT_DIR for NSIS bundling.
/// Tauri v2 with x86_64-pc-windows-gnu doesn't always include this automatically.
/// We prefer a pre-existing copy in resources/webview2/ (manually placed before build)
/// because build.rs runs BEFORE webview2-com-sys compiles, so target/release/ may not
/// have it yet on clean builds.
fn bundle_webview2_loader(manifest_path: &Path) -> Vec<String> {
    let out_dir = env::var("OUT_DIR").unwrap();
    let resources_dir = Path::new(&out_dir).join("resources/webview2");
    let _ = fs::create_dir_all(&resources_dir);
    let dst = resources_dir.join("WebView2Loader.dll");

    // If already in OUT_DIR/resources (pre-copied before build), use it directly
    if dst.exists() {
        println!("cargo:warning=Bundled WebView2Loader.dll (pre-existing): {}", dst.display());
        return vec!["resources/webview2/WebView2Loader.dll".to_string()];
    }

    // Copy from source resources/webview2/ (committed to repo)
    let src = manifest_path.join("resources/webview2/WebView2Loader.dll");
    if src.exists() {
        fs::copy(&src, &dst).expect("Failed to copy WebView2Loader.dll");
        println!("cargo:warning=Bundled WebView2Loader.dll: {}", src.display());
        return vec!["resources/webview2/WebView2Loader.dll".to_string()];
    }

    // Fallback: search build output directories (works on incremental builds)
    let build_base = manifest_path.join("../target/release/build");
    if let Ok(entries) = fs::read_dir(&build_base) {
        for entry in entries.flatten() {
            for arch in &["x64", "x86", "arm64"] {
                let candidate = entry.path().join("out").join(arch).join("WebView2Loader.dll");
                if candidate.exists() {
                    fs::copy(&candidate, &dst).expect("Failed to copy WebView2Loader.dll");
                    println!("cargo:warning=Bundled WebView2Loader.dll (fallback): {}", candidate.display());
                    return vec!["resources/webview2/WebView2Loader.dll".to_string()];
                }
            }
        }
    }

    println!("cargo:warning=WebView2Loader.dll not found - app will require WebView2 Runtime installed");
    vec![]
}

fn template_tauri_conf(tenant_id: &str, commercial_name: &str, extra_resources: &[String], out_dir: &Path) {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let tauri_conf_path = Path::new(&manifest_dir).join("tauri.conf.json");
    let content = fs::read_to_string(&tauri_conf_path).expect("Failed to read tauri.conf.json");
    
    // Parse and modify
    let mut conf: serde_json::Value = serde_json::from_str(&content).expect("Invalid tauri.conf.json");
    
    conf["identifier"] = serde_json::Value::String(format!("com.mindledger.{}.desktop", tenant_id));
    // Product name is always "MindLedger"; window title uses tenant branding
    conf["productName"] = serde_json::Value::String("MindLedger".to_string());
    conf["app"]["windows"][0]["title"] = serde_json::Value::String(commercial_name.to_string());

    // Always set resources from scratch (avoids duplicate accumulation across builds)
    conf["bundle"]["resources"] = serde_json::Value::Array(
        extra_resources.iter().map(|r| serde_json::Value::String(r.clone())).collect()
    );
    
    // Write to OUT_DIR (build artifact), NOT source - keeps git clean
    let generated_path = out_dir.join("tauri.conf.json");
    let new_content = serde_json::to_string_pretty(&conf).expect("Failed to serialize tauri.conf.json");
    fs::write(&generated_path, new_content).expect("Failed to write generated tauri.conf.json");
    
    // Tell tauri-build to use our generated config (compact inline JSON, no newlines)
    let compact_json = serde_json::to_string(&conf).expect("Failed to serialize compact tauri.conf.json");
    println!("cargo:rustc-env=TAURI_CONFIG={}", compact_json);
}

/// Generate a Rust module with embedded tenant config for compile-time inclusion
fn generate_tenant_config_module(config_str: &str, out_dir: &Path) {
    let module_content = format!(
        r#"// Auto-generated by build.rs - DO NOT EDIT
/// Embedded tenant configuration JSON
pub const TENANT_CONFIG_JSON: &str = {json_str};
"#,
        json_str = serde_json::to_string(config_str).expect("Failed to serialize config as string literal")
    );
    
    let module_path = out_dir.join("tenant_config.rs");
    fs::write(&module_path, module_content).expect("Failed to write tenant_config.rs");
    
    // Emit the path so the library crate can include it
    println!("cargo:rustc-env=TENANT_CONFIG_RS_PATH={}", module_path.display());
}