use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let manifest_path = Path::new(&manifest_dir);

    // Load .env file generated by bundle-tenant.py (if present)
    // Falls back gracefully when building without the bundler
    let env_path = manifest_path.join(".env");
    if env_path.exists() {
        let env_content = fs::read_to_string(&env_path).unwrap_or_default();
        for line in env_content.lines() {
            let line = line.trim();
            if line.starts_with("TENANT_CONFIG=") {
                let value = line["TENANT_CONFIG=".len()..].trim();
                // Remove surrounding quotes if present
                let value = value.trim_matches('"').trim_matches('\'');
                env::set_var("TENANT_CONFIG", value);
                break;
            }
        }
    }

    // Track tenant config changes for rebuild
    // TENANT_CONFIG is set by bundle-tenant.py via .env
    // Falls back to legacy default for backward compatibility
    let tenant_config_path = env::var("TENANT_CONFIG")
        .unwrap_or_else(|_| manifest_path.join("../tenant-configs/default.json").to_string_lossy().into_owned());

    let config_path = Path::new(&tenant_config_path);
    if config_path.exists() {
        println!("cargo:rerun-if-changed={}", config_path.display());

        // Read and copy tenant config to OUT_DIR for runtime inclusion
        let out_dir = env::var("OUT_DIR").unwrap();
        let dest_path = Path::new(&out_dir).join("tenant-config.json");
        fs::copy(config_path, &dest_path)
            .expect("Failed to copy tenant config to OUT_DIR");

        // Parse to validate JSON
        let config_str = fs::read_to_string(config_path)
            .expect("Failed to read tenant config");
        let config: serde_json::Value = serde_json::from_str(&config_str)
            .expect("Tenant config is not valid JSON");

        // Emit env var for runtime access to the config file path
        println!("cargo:rustc-env=TENANT_CONFIG_PATH={}", dest_path.display());

        // Also embed the config JSON content as an env var so any crate can read it at compile time.
        // MUST use compact JSON (no newlines) — cargo:rustc-env reads line-by-line and
        // newlines in the value would truncate the embedded content.
        let compact_json = serde_json::to_string(&config)
            .expect("Failed to compact tenant config JSON for env var");
        println!("cargo:rustc-env=TENANT_CONFIG_JSON={}", compact_json);

        // Template tauri.conf.json with tenant-specific values
        let tenant_id = config["tenant"]["id"].as_str().unwrap_or("default");
        let commercial_name = config["tenant"]["commercialName"].as_str().unwrap_or("MindLedger");

        // Bundle runtime DLLs on Windows targets (OpenSSL + WebView2)
        let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
        let resources = if target_os == "windows" {
            // Ensure openssl-sys can find the correct-arch import libs and headers
            set_openssl_env_vars();
            let mut r = bundle_openssl_dlls(manifest_path);
            r.extend(bundle_webview2_loader(manifest_path));
            r
        } else {
            vec![]
        };

        template_tauri_conf(tenant_id, commercial_name, &resources, Path::new(&out_dir));
    }

    // On Windows: patch the NSIS hook in-place with absolute DLL paths.
    // tauri_build::build() only generates config — the actual NSIS compilation
    // (makensis) happens AFTER build.rs returns, during the tauri CLI post-build step.
    // So we must NOT restore the hook here; leave it patched for makensis to find.
    // The hook is reset by `git checkout` before each clean build.
    if cfg!(windows) {
        patch_nsis_hook_in_place(manifest_path);
    }

    tauri_build::build()
}

/// Copy OpenSSL DLLs from vcpkg to resources/ and return their relative paths for bundling.
/// Detects target architecture to use correct DLL names (x64 vs arm64).
/// Uses CARGO_CFG_TARGET_ARCH (set by cargo) for reliable arch detection.
///
/// CRITICAL: This function MUST find arch-specific DLLs. Bundling the wrong
/// architecture (e.g. x64 DLLs in an ARM64 build) causes 0xc000007b crashes.
fn bundle_openssl_dlls(manifest_path: &Path) -> Vec<String> {
    let target_arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
    let arch_suffix = if target_arch == "aarch64" {
        "arm64"
    } else {
        "x64"
    };
    let vcpkg_triplet = if target_arch == "aarch64" {
        "arm64-windows"
    } else {
        "x64-windows"
    };

    println!("cargo:warning=OpenSSL bundle: target_arch={}, arch_suffix={}, triplet={}", target_arch, arch_suffix, vcpkg_triplet);

    // Build ordered search paths: vcpkg first (authoritative), then OPENSSL_DIR, then fallback
    let home = env::var("USERPROFILE").unwrap_or_default();
    let vcpkg_root = env::var("VCPKG_INSTALLATION_ROOT").unwrap_or_default();

    let search_paths: Vec<PathBuf> = [
        // 1. vcpkg installed directory (CI and local with vcpkg)
        if !vcpkg_root.is_empty() {
            vec![Path::new(&vcpkg_root).join(format!("installed/{}", vcpkg_triplet)).join("bin")]
        } else {
            vec![]
        },
        // 2. OPENSSL_DIR env var (explicit override)
        if let Ok(openssl_dir) = env::var("OPENSSL_DIR") {
            vec![Path::new(&openssl_dir).join("bin")]
        } else {
            vec![]
        },
        // 3. Common local installation paths
        vec![
            Path::new(&home).join(format!("vcpkg/installed/{}/bin", vcpkg_triplet)),
            Path::new(&home).join("scoop/apps/mingw/current/opt/bin"),
            PathBuf::from("C:/Program Files/OpenSSL/bin"),
            PathBuf::from("C:/Program Files (x86)/OpenSSL/bin"),
        ],
    ].concat();

    let resources_dir = manifest_path.join("resources/openssl");
    let _ = fs::create_dir_all(&resources_dir);

    let mut resources = vec![];
    let mut missing_dlls: Vec<String> = vec![];

    // Arch-specific DLL names — MUST match exactly
    let crypto_name = format!("libcrypto-3-{}.dll", arch_suffix);
    let ssl_name = format!("libssl-3-{}.dll", arch_suffix);

    // Find and copy crypto DLL
    match find_and_copy_dll(&crypto_name, &search_paths, &resources_dir) {
        Some(relative_path) => {
            resources.push(relative_path);
            println!("cargo:warning=Bundled OpenSSL DLL: {}", crypto_name);
        }
        None => {
            missing_dlls.push(crypto_name.clone());
            println!("cargo:error=CRITICAL: {} not found in any search path", crypto_name);
            println!("cargo:error=Searched:");
            for path in &search_paths {
                println!("cargo:error=  {}", path.display());
            }
            println!("cargo:error=Fix: Set OPENSSL_DIR to vcpkg installed root, or install vcpkg with: vcpkg install openssl:{}", vcpkg_triplet);
        }
    }

    // Find and copy SSL DLL
    match find_and_copy_dll(&ssl_name, &search_paths, &resources_dir) {
        Some(relative_path) => {
            resources.push(relative_path);
            println!("cargo:warning=Bundled OpenSSL DLL: {}", ssl_name);
        }
        None => {
            missing_dlls.push(ssl_name.clone());
            println!("cargo:error=CRITICAL: {} not found in any search path", ssl_name);
        }
    }

    // FAIL FAST: Do not produce a broken installer with missing or wrong-arch DLLs
    if !missing_dlls.is_empty() {
        panic!(
            "OpenSSL DLL bundling FAILED for target {}. Missing: {}. \
             Cannot build installer without correct-arch OpenSSL DLLs. \
             Set OPENSSL_DIR or install vcpkg openssl:{}",
            target_arch,
            missing_dlls.join(", "),
            vcpkg_triplet
        );
    }

    resources
}

/// Search for a DLL in ordered search paths, copy to dest, return relative resource path.
/// Returns None if not found in any path.
fn find_and_copy_dll(dll_name: &str, search_paths: &[PathBuf], dest_dir: &Path) -> Option<String> {
    for search_path in search_paths {
        let candidate = search_path.join(dll_name);
        if candidate.exists() {
            let dst = dest_dir.join(dll_name);
            fs::copy(&candidate, &dst).unwrap_or_else(|e| {
                panic!("Failed to copy {} to {}: {}", candidate.display(), dst.display(), e);
            });
            println!("cargo:warning=Copied {} from {}", dll_name, candidate.display());
            return Some(format!("resources/openssl/{}", dll_name));
        }
    }
    None
}

/// Set OPENSSL_LIB_DIR and OPENSSL_INCLUDE_DIR for the openssl-sys crate.
/// This ensures the Rust compiler finds the correct-arch import libs (.lib) and headers.
/// Only sets them if not already set by the user/CI.
fn set_openssl_env_vars() {
    let target_arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
    let vcpkg_triplet = if target_arch == "aarch64" {
        "arm64-windows"
    } else {
        "x64-windows"
    };

    // If OPENSSL_LIB_DIR is already set, respect it
    if env::var("OPENSSL_LIB_DIR").is_ok() {
        return;
    }

    // Try vcpkg installed directory
    let vcpkg_root = env::var("VCPKG_INSTALLATION_ROOT").unwrap_or_default();
    let installed_dir = Path::new(&vcpkg_root).join("installed").join(vcpkg_triplet);

    if installed_dir.exists() {
        let lib_dir = installed_dir.join("lib");
        let include_dir = installed_dir.join("include");
        if lib_dir.exists() {
            env::set_var("OPENSSL_LIB_DIR", lib_dir.to_str().unwrap_or_default());
            println!("cargo:warning=Set OPENSSL_LIB_DIR={}", lib_dir.display());
        }
        if include_dir.exists() {
            env::set_var("OPENSSL_INCLUDE_DIR", include_dir.to_str().unwrap_or_default());
            println!("cargo:warning=Set OPENSSL_INCLUDE_DIR={}", include_dir.display());
        }
    }
}

/// Patch the NSIS hook file in-place with absolute DLL paths before tauri_build runs.
///
/// The NSIS compiler (makensis) runs from a temp directory, so relative paths in
/// `installer-hooks.nsh` don't resolve. This function replaces the
/// `!include "dll-paths.nsh"` directive with inline `!define` statements containing
/// absolute paths. Returns the original content for restoration after build.
fn patch_nsis_hook_in_place(manifest_path: &Path) -> Option<String> {
    let resources_dir = manifest_path.join("resources/openssl");
    let webview_dir = manifest_path.join("resources/webview2");
    let hook_path = manifest_path.join("nsis-hooks/installer-hooks.nsh");

    let original = fs::read_to_string(&hook_path).ok()?;

    // Build the !define block with absolute paths
    let target_arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
    let arch_suffix = if target_arch == "aarch64" { "arm64" } else { "x64" };

    let mut defines = vec![
        "; Auto-generated by build.rs - DO NOT EDIT".to_string(),
        "; Contains absolute paths to DLLs for NSIS File commands.".to_string(),
        "; Regenerated on every build.".to_string(),
        "".to_string(),
    ];

    // OpenSSL libcrypto
    let crypto_name = format!("libcrypto-3-{}.dll", arch_suffix);
    let crypto_path = resources_dir.join(&crypto_name);
    if crypto_path.exists() {
        let abs = crypto_path.to_str().unwrap_or_default();
        defines.push(format!("!define NSIS_DLL_CRYPTO \"{}\"", abs));
        println!("cargo:warning=NSIS DLL path: {} -> {}", crypto_name, abs);
    } else {
        println!("cargo:warning=NSIS: {} not found, skipping", crypto_name);
    }

    // OpenSSL libssl
    let ssl_name = format!("libssl-3-{}.dll", arch_suffix);
    let ssl_path = resources_dir.join(&ssl_name);
    if ssl_path.exists() {
        let abs = ssl_path.to_str().unwrap_or_default();
        defines.push(format!("!define NSIS_DLL_SSL \"{}\"", abs));
    }

    // WebView2Loader.dll
    let wv2_path = webview_dir.join("WebView2Loader.dll");
    if wv2_path.exists() {
        let abs = wv2_path.to_str().unwrap_or_default();
        defines.push(format!("!define NSIS_DLL_WEBVIEW2 \"{}\"", abs));
    }

    defines.push("".to_string());
    let defines_block = defines.join("\n");

    // Replace the include directive with the inlined defines.
    // Try both LF and CRLF line endings since git may checkout with either.
    let marker_lf = "; Include auto-generated absolute paths to DLLs (written by build.rs)\n!include \"dll-paths.nsh\"";
    let marker_crlf = "; Include auto-generated absolute paths to DLLs (written by build.rs)\r\n!include \"dll-paths.nsh\"";
    let patched = if let Some(pos) = original.find(marker_lf) {
        let mut p = original.clone();
        p.replace_range(pos..pos + marker_lf.len(), &defines_block);
        p
    } else if let Some(pos) = original.find(marker_crlf) {
        let mut p = original.clone();
        p.replace_range(pos..pos + marker_crlf.len(), &defines_block);
        p
    } else {
        println!("cargo:warning=NSIS hook patch marker not found, skipping patch");
        return None;
    };

    if patched != original {
        fs::write(&hook_path, &patched).expect("Failed to patch nsis-hooks/installer-hooks.nsh");
        println!("cargo:warning=Patched NSIS hook with absolute DLL paths");
        Some(original)
    } else {
        println!("cargo:warning=NSIS hook patch marker not found, skipping patch");
        None
    }
}

/// Copy WebView2Loader.dll from pre-staged resources/ to OUT_DIR for NSIS bundling.
/// Tauri v2 with x86_64-pc-windows-gnu doesn't always include this automatically.
/// We prefer a pre-existing copy in resources/webview2/ (manually placed before build)
/// because build.rs runs BEFORE webview2-com-sys compiles, so target/release/ may not
/// have it yet on clean builds.
fn bundle_webview2_loader(manifest_path: &Path) -> Vec<String> {
    let out_dir = env::var("OUT_DIR").unwrap();
    let resources_dir = Path::new(&out_dir).join("resources/webview2");
    let _ = fs::create_dir_all(&resources_dir);
    let dst = resources_dir.join("WebView2Loader.dll");

    // If already in OUT_DIR/resources (pre-copied before build), use it directly
    if dst.exists() {
        println!("cargo:warning=Bundled WebView2Loader.dll (pre-existing): {}", dst.display());
        return vec!["resources/webview2/WebView2Loader.dll".to_string()];
    }

    // Copy from source resources/webview2/ (committed to repo)
    let src = manifest_path.join("resources/webview2/WebView2Loader.dll");
    if src.exists() {
        fs::copy(&src, &dst).expect("Failed to copy WebView2Loader.dll");
        println!("cargo:warning=Bundled WebView2Loader.dll: {}", src.display());
        return vec!["resources/webview2/WebView2Loader.dll".to_string()];
    }

    // Fallback: search build output directories (works on incremental builds)
    let build_base = manifest_path.join("../target/release/build");
    if let Ok(entries) = fs::read_dir(&build_base) {
        for entry in entries.flatten() {
            for arch in &["x64", "x86", "arm64"] {
                let candidate = entry.path().join("out").join(arch).join("WebView2Loader.dll");
                if candidate.exists() {
                    fs::copy(&candidate, &dst).expect("Failed to copy WebView2Loader.dll");
                    println!("cargo:warning=Bundled WebView2Loader.dll (fallback): {}", candidate.display());
                    return vec!["resources/webview2/WebView2Loader.dll".to_string()];
                }
            }
        }
    }

    println!("cargo:warning=WebView2Loader.dll not found - app will require WebView2 Runtime installed");
    vec![]
}

fn template_tauri_conf(tenant_id: &str, commercial_name: &str, extra_resources: &[String], out_dir: &Path) {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let tauri_conf_path = Path::new(&manifest_dir).join("tauri.conf.json");
    let content = fs::read_to_string(&tauri_conf_path).expect("Failed to read tauri.conf.json");
    
    // Parse and modify
    let mut conf: serde_json::Value = serde_json::from_str(&content).expect("Invalid tauri.conf.json");
    
    conf["identifier"] = serde_json::Value::String(format!("com.mindledger.{}.desktop", tenant_id));
    // Product name is always "MindLedger"; window title uses tenant branding
    conf["productName"] = serde_json::Value::String("MindLedger".to_string());
    conf["app"]["windows"][0]["title"] = serde_json::Value::String(commercial_name.to_string());

    // Always set resources from scratch (avoids duplicate accumulation across builds)
    conf["bundle"]["resources"] = serde_json::Value::Array(
        extra_resources.iter().map(|r| serde_json::Value::String(r.clone())).collect()
    );
    
    // Write to OUT_DIR (build artifact) — tauri_build::build() reads from here
    let generated_path = out_dir.join("tauri.conf.json");
    let new_content = serde_json::to_string_pretty(&conf).expect("Failed to serialize tauri.conf.json");
    fs::write(&generated_path, &new_content).expect("Failed to write generated tauri.conf.json");

    // Write compact (no-newlines) version to source tauri.conf.json so tauri_build::build()
    // picks it up via its normal file-reading path. cargo:rustc-env alone is insufficient
    // because it only sets env vars for the *compiler*, not for the build script process.
    fs::write(&tauri_conf_path, &new_content).expect("Failed to write patched tauri.conf.json");

    // Tell the compiled binary which config to use at runtime
    let compact_json = serde_json::to_string(&conf).expect("Failed to serialize compact tauri.conf.json");
    println!("cargo:rustc-env=TAURI_CONFIG={}", compact_json);
}