[package]
name = "soft-mindledger-application"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }

[dependencies]
soft-mindledger-domain = { path = "../domain" }
thiserror = { workspace = true }
tracing = { workspace = true }
mockall = { workspace = true, optional = true }
anyhow = "1.0"
docx-rs = "0.4"

[dev-dependencies]
mockall = { workspace = true }
rstest = { workspace = true }
proptest = { workspace = true }
tempfile = { workspace = true }